"""Constants for the ESP32 RSSI Integration."""
DOMAIN = "esp32_rssi"
CONF_RESOURCE = "resource"
CONF_DEVICE_ID = "device_id"
BASE_URL = "https://alva.azurewebsites.net/api/get_latest_data?device_id={}"
